// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Local security patch: HTTP transport auth + loopback default (issue #26).

package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"
	"strings"

	"github.com/mark3labs/mcp-go/server"
	"github.com/ph-commons/pagasa-pp-cli/internal/cli"
	mcptools "github.com/ph-commons/pagasa-pp-cli/internal/mcp"
)

// Transport selection order: --transport flag, then PP_MCP_TRANSPORT env,
// then the first transport declared in the spec (see MCPConfig.Transport).
// The flag surface lets one binary serve stdio locally and streamable HTTP
// when hosted in a container or remote sandbox, matching the Anthropic
// guidance that production agents need a remote option.
//
// HTTP transport is fail-closed (#26): default bind is loopback only,
// non-loopback requires --allow-remote, and every HTTP request needs a
// bearer token (--token or PP_MCP_TOKEN). Default transport remains stdio
// (no listening socket).

func main() {
	// Pin the learn-event surface for this process and every walker
	// shell-out child, so usage events record surface=mcp.
	_ = os.Setenv("PAGASA_LEARN_SURFACE", "mcp")
	if err := cli.BindMCPServerProfile(); err != nil {
		fmt.Fprintf(os.Stderr, "MCP client-profile bind failed: %v\n", err)
		os.Exit(1)
	}
	// Version shares internal/cli resolution (ldflags → module → VCS → 0.0.0-dev).
	s := server.NewMCPServer(
		"Pagasa",
		cli.Version(),
		server.WithToolCapabilities(false),
	)

	mcptools.RegisterTools(s)

	transport := flag.String("transport", defaultTransport(), "MCP transport: stdio | http")
	addr := flag.String("addr", defaultHTTPAddr, "bind address for http transport (default loopback 127.0.0.1:7777)")
	token := flag.String("token", "", "bearer token required for http transport (or set "+envMCPToken+")")
	allowRemote := flag.Bool("allow-remote", false, "allow non-loopback http --addr (still requires --token)")
	flag.Parse()

	switch strings.ToLower(*transport) {
	case "stdio":
		if err := server.ServeStdio(s); err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			os.Exit(1)
		}
	case "http":
		secret := resolveHTTPToken(*token)
		if err := requireHTTPToken(secret); err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			os.Exit(2)
		}
		if err := validateHTTPListen(*addr, *allowRemote); err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			os.Exit(2)
		}
		// Serve via our mux + bearer middleware. StreamableHTTPServer is an
		// http.Handler; we do not call Start() so we control auth and path.
		mcpHTTP := server.NewStreamableHTTPServer(s)
		handler := newHTTPMCPHandler(secret, mcpHTTP)
		fmt.Fprintf(os.Stderr, "pagasa-pp-mcp serving MCP over streamable HTTP at http://%s%s (bearer auth required)\n", *addr, mcpHTTPPath)
		if err := http.ListenAndServe(*addr, handler); err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Fprintf(os.Stderr, "unknown --transport %q (supported: stdio, http)\n", *transport)
		os.Exit(2)
	}
}

// defaultTransport reads PP_MCP_TRANSPORT env when set, otherwise falls back
// to "stdio" so running the binary with no args keeps today's behavior.
// Container-hosted agents can pin the transport via env without a flag, which
// matches how hosted-agent process supervisors typically pass configuration.
func defaultTransport() string {
	if t := os.Getenv("PP_MCP_TRANSPORT"); t != "" {
		return t
	}
	return "stdio"
}
