// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ph-commons/pagasa-pp-cli/internal/cliutil"
	"github.com/ph-commons/pagasa-pp-cli/internal/store"
)

func withMCPSurface(t *testing.T) {
	t.Helper()
	prev := store.LearnEventSurface()
	store.SetLearnEventSurface(store.LearnSurfaceMCP)
	t.Cleanup(func() {
		store.SetLearnEventSurface(prev)
	})
}

func TestRejectPathOutsideMCPAppDirs_CLIAllowsAnywhere(t *testing.T) {
	store.SetLearnEventSurface(store.LearnSurfaceCLI)
	t.Cleanup(func() { store.SetLearnEventSurface("") })
	evil := filepath.Join(t.TempDir(), "outside.db")
	if err := rejectPathOutsideMCPAppDirs(evil, "--db"); err != nil {
		t.Fatalf("CLI surface should allow arbitrary paths: %v", err)
	}
}

func TestRejectPathOutsideMCPAppDirs_MCPRejectsOutside(t *testing.T) {
	withMCPSurface(t)
	home := t.TempDir()
	t.Setenv("HOME", home)
	// Reset path home override so DataDir/StateDir resolve under HOME.
	restore, err := cliutil.SetHomeOverride("")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(restore)

	evil := filepath.Join(t.TempDir(), "secret.db")
	err = rejectPathOutsideMCPAppDirs(evil, "--db")
	if err == nil {
		t.Fatal("expected rejection for path outside data/state")
	}
	if !strings.Contains(err.Error(), "outside MCP-allowed") {
		t.Fatalf("error = %v", err)
	}
}

func TestRejectPathOutsideMCPAppDirs_MCPAllowsDataDir(t *testing.T) {
	withMCPSurface(t)
	home := t.TempDir()
	t.Setenv("HOME", home)
	restore, err := cliutil.SetHomeOverride("")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(restore)

	dataDir, err := cliutil.DataDir()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		t.Fatal(err)
	}
	okPath := filepath.Join(dataDir, "ok.db")
	if err := rejectPathOutsideMCPAppDirs(okPath, "--db"); err != nil {
		t.Fatalf("data dir path should be allowed: %v", err)
	}
}

func TestRejectPathOutsideMCPAppDirs_MCPAllowsStateDir(t *testing.T) {
	withMCPSurface(t)
	home := t.TempDir()
	t.Setenv("HOME", home)
	restore, err := cliutil.SetHomeOverride("")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(restore)

	stateDir, err := cliutil.StateDir()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(stateDir, 0o755); err != nil {
		t.Fatal(err)
	}
	okPath := filepath.Join(stateDir, "notes.md")
	if err := rejectPathOutsideMCPAppDirs(okPath, "--notes-file"); err != nil {
		t.Fatalf("state dir path should be allowed: %v", err)
	}
}

func TestRejectPathOutsideMCPAppDirs_MCPBlocksTraversal(t *testing.T) {
	withMCPSurface(t)
	home := t.TempDir()
	t.Setenv("HOME", home)
	restore, err := cliutil.SetHomeOverride("")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(restore)

	dataDir, err := cliutil.DataDir()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		t.Fatal(err)
	}
	// Construct a path that cleans to outside via ..
	evil := filepath.Join(dataDir, "..", "..", "etc", "passwd")
	if err := rejectPathOutsideMCPAppDirs(evil, "--playbook-file"); err == nil {
		t.Fatal("expected rejection for .. traversal outside roots")
	}
}

func TestResolveLearnDBPath_MCPDefaultOK(t *testing.T) {
	withMCPSurface(t)
	home := t.TempDir()
	t.Setenv("HOME", home)
	restore, err := cliutil.SetHomeOverride("")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(restore)

	p, err := resolveLearnDBPath("")
	if err != nil {
		t.Fatalf("default db under MCP: %v", err)
	}
	dataDir, err := cliutil.DataDir()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(p, dataDir) {
		t.Fatalf("default path %q not under data dir %q", p, dataDir)
	}
}

func TestResolvePlaybookInputs_MCPRejectsOutsideFile(t *testing.T) {
	withMCPSurface(t)
	home := t.TempDir()
	t.Setenv("HOME", home)
	restore, err := cliutil.SetHomeOverride("")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(restore)

	evil := filepath.Join(t.TempDir(), "p.json")
	if err := os.WriteFile(evil, []byte(`{"steps":[]}`), 0o600); err != nil {
		t.Fatal(err)
	}
	_, _, err = resolvePlaybookInputs(evil, "", "")
	if err == nil {
		t.Fatal("expected playbook-file outside roots to fail under MCP")
	}
	if !strings.Contains(err.Error(), "outside MCP-allowed") {
		t.Fatalf("error = %v", err)
	}
}

func TestResolvePlaybookInputs_MCPAllowsInlineNotesWithoutFile(t *testing.T) {
	withMCPSurface(t)
	// Inline notes only — no file path to gate.
	pb, notes, err := resolvePlaybookInputs("", "gotcha note", "")
	if err != nil {
		t.Fatalf("inline notes under MCP: %v", err)
	}
	if pb != "" || notes != "gotcha note" {
		t.Fatalf("got pb=%q notes=%q", pb, notes)
	}
}
