// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ph-commons/pagasa-pp-cli/internal/cliutil"
	"github.com/ph-commons/pagasa-pp-cli/internal/store"
)

// rejectPathOutsideMCPAppDirs enforces issue #30 / F10: under the MCP
// surface, --db and teach/playbook *-file paths must resolve inside the
// app data or state directories. CLI TTY operators keep full path flexibility.
// Empty path is a no-op (caller uses defaults which already live under data).
func rejectPathOutsideMCPAppDirs(path, flag string) error {
	if store.LearnEventSurface() != store.LearnSurfaceMCP {
		return nil
	}
	path = strings.TrimSpace(path)
	if path == "" {
		return nil
	}
	ok, err := pathWithinMCPAppDirs(path)
	if err != nil {
		return fmt.Errorf("%s: %w", flag, err)
	}
	if !ok {
		return fmt.Errorf("%s %q is outside MCP-allowed data/state directories; use the default path, place files under the app data/state dir, or pass content inline (--playbook-json / --notes)", flag, path)
	}
	return nil
}

// resolveLearnDBPath is learnDBPath plus the MCP allowlist gate.
func resolveLearnDBPath(explicit string) (string, error) {
	path := learnDBPath(explicit)
	if err := rejectPathOutsideMCPAppDirs(path, "--db"); err != nil {
		return "", err
	}
	return path, nil
}

func pathWithinMCPAppDirs(path string) (bool, error) {
	roots, err := mcpAppDirRoots()
	if err != nil {
		return false, err
	}
	candidate, err := absCleanPath(path)
	if err != nil {
		return false, err
	}
	candidate, err = resolveExistingOrParent(candidate)
	if err != nil {
		return false, err
	}
	for _, root := range roots {
		rootAbs, err := absCleanPath(root)
		if err != nil {
			continue
		}
		if resolved, rerr := filepath.EvalSymlinks(rootAbs); rerr == nil {
			rootAbs = resolved
		}
		if pathIsUnder(rootAbs, candidate) {
			return true, nil
		}
	}
	return false, nil
}

func mcpAppDirRoots() ([]string, error) {
	var roots []string
	for _, fn := range []func() (string, error){cliutil.DataDir, cliutil.StateDir} {
		d, err := fn()
		if err != nil {
			continue
		}
		d = strings.TrimSpace(d)
		if d != "" {
			roots = append(roots, d)
		}
	}
	if len(roots) == 0 {
		return nil, fmt.Errorf("resolve app data/state directories")
	}
	return roots, nil
}

func absCleanPath(path string) (string, error) {
	path = filepath.Clean(cliutilExpandTilde(path))
	if path == "" {
		return "", fmt.Errorf("empty path")
	}
	if filepath.IsAbs(path) {
		return path, nil
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	return filepath.Clean(abs), nil
}

// cliutilExpandTilde mirrors cliutil tilde expansion without exporting it.
func cliutilExpandTilde(path string) string {
	path = strings.TrimSpace(path)
	if path == "~" {
		if home, err := os.UserHomeDir(); err == nil {
			return home
		}
		return path
	}
	if strings.HasPrefix(path, "~/") {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, strings.TrimPrefix(path, "~/"))
		}
	}
	return path
}

func resolveExistingOrParent(path string) (string, error) {
	if resolved, err := filepath.EvalSymlinks(path); err == nil {
		return resolved, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		// dangling intermediate symlink etc. — still try parent for new files
	}
	dir := filepath.Dir(path)
	base := filepath.Base(path)
	if resolvedDir, err := filepath.EvalSymlinks(dir); err == nil {
		return filepath.Join(resolvedDir, base), nil
	}
	// Parent may not exist yet either; keep cleaned abs path for prefix check.
	return path, nil
}

func pathIsUnder(root, target string) bool {
	rel, err := filepath.Rel(root, target)
	if err != nil {
		return false
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(os.PathSeparator)) {
		return false
	}
	return true
}
