// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"
	"unicode/utf8"

	"github.com/ph-commons/pagasa-pp-cli/internal/config"
	"github.com/ph-commons/pagasa-pp-cli/internal/platform"
)

func TestAPIError_ErrorOmitsBody(t *testing.T) {
	t.Parallel()

	html := "<!DOCTYPE html><html><body>" + strings.Repeat("WAF challenge page noise ", 200) + "</body></html>"
	err := &APIError{
		Method:     "GET",
		Path:       "https://www.pagasa.dost.gov.ph/weather",
		StatusCode: 503,
		Body:       html,
	}
	msg := err.Error()
	if strings.Contains(msg, "WAF") || strings.Contains(msg, "<!DOCTYPE") || strings.Contains(msg, "<html") {
		t.Fatalf("Error() leaked body content: %q", msg)
	}
	if !strings.Contains(msg, "HTTP 503") {
		t.Fatalf("Error() missing status: %q", msg)
	}
	if !strings.Contains(msg, "upstream server error") {
		t.Fatalf("Error() missing class: %q", msg)
	}
	// Body field still available for doctor-style diagnostics.
	if err.Body != html {
		t.Fatalf("Body field should retain diagnostic snippet")
	}
}

func TestAPIError_ErrorClasses(t *testing.T) {
	t.Parallel()
	cases := []struct {
		code int
		want string
	}{
		{401, "auth/permission"},
		{403, "auth/permission"},
		{404, "not found"},
		{409, "conflict"},
		{429, "rate limited"},
		{400, "upstream client error"},
		{502, "upstream server error"},
	}
	for _, tc := range cases {
		msg := (&APIError{Method: "GET", Path: "/x", StatusCode: tc.code}).Error()
		if !strings.Contains(msg, tc.want) {
			t.Errorf("HTTP %d: got %q, want class %q", tc.code, msg, tc.want)
		}
	}
}

func TestTruncateBody(t *testing.T) {
	t.Parallel()

	const maxBytes = 4096

	cases := []struct {
		name        string
		input       []byte
		wantLen     int
		wantHasTail bool
	}{
		{"empty", nil, 0, false},
		{"under cap", []byte("hello"), 5, false},
		{"at cap", bytes.Repeat([]byte("a"), maxBytes), maxBytes, false},
		{"one over cap", bytes.Repeat([]byte("a"), maxBytes+1), maxBytes + 3, true},
		{"huge body", bytes.Repeat([]byte("a"), maxBytes*8), maxBytes + 3, true},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := truncateBody(tc.input)
			if len(got) != tc.wantLen {
				t.Fatalf("len = %d, want %d", len(got), tc.wantLen)
			}
			if tc.wantHasTail && !strings.HasSuffix(got, "...") {
				t.Fatalf("want trailing %q", "...")
			}
			if !tc.wantHasTail && strings.HasSuffix(got, "...") {
				t.Fatalf("unexpected trailing %q in %q", "...", got)
			}
		})
	}
}

func TestTruncateBody_UTF8RuneAtBoundary(t *testing.T) {
	t.Parallel()

	// '€' is 3 bytes (0xE2 0x82 0xAC). Place it so the slice at byte 4096 cuts
	// mid-rune; strings.ToValidUTF8 should drop the partial rune cleanly rather
	// than emit U+FFFD or invalid UTF-8.
	prefix := strings.Repeat("a", 4094)
	body := []byte(prefix + "€" + strings.Repeat("b", 100))
	got := truncateBody(body)

	if !utf8.ValidString(got) {
		t.Fatalf("output is not valid UTF-8")
	}
	if strings.ContainsRune(got, utf8.RuneError) {
		t.Fatalf("output contains replacement rune U+FFFD")
	}
	if !strings.HasSuffix(got, "...") {
		t.Fatalf("want trailing %q", "...")
	}
	// Partial rune must be dropped, not replaced: 4094 valid bytes + "...".
	if want := 4094 + 3; len(got) != want {
		t.Fatalf("len = %d, want %d (partial rune should be dropped, not replaced)", len(got), want)
	}
}

func TestCacheKeyDelimitsSortedQueryParams(t *testing.T) {
	t.Parallel()

	c := &Client{BaseURL: "https://api.example.test"}
	collidingTwoParams := c.cacheKey("/titles", map[string]string{
		"country": "USAformat",
		"year":    "bluray",
	})
	collidingThreeParams := c.cacheKey("/titles", map[string]string{
		"country": "USA",
		"format":  "bluray",
		"year":    "",
	})
	if collidingTwoParams == collidingThreeParams {
		t.Fatalf("cache keys collided for adjacent query params: %q", collidingTwoParams)
	}

	first := c.cacheKey("/titles", map[string]string{"format": "4k", "country": "USA"})
	second := c.cacheKey("/titles", map[string]string{"country": "USA", "format": "4k"})
	if first != second {
		t.Fatalf("cache key should be deterministic regardless of map order: %q != %q", first, second)
	}
}

func TestPlatformCacheKeyContract(t *testing.T) {
	newClient := func() *Client {
		c := &Client{BaseURL: "https://api.example.test"}
		err := c.BindPlatformSession(&platform.Session{
			Profile: &platform.Profile{Name: "tenant-a"}, ProfileName: "tenant-a", CLI: "sample", Source: "sample",
			CredentialFingerprint: "machine-keyed-fingerprint-a",
			ExpectedIdentity:      map[string]string{"account_id": "a"}, ObservedIdentity: map[string]string{"account_id": "a"},
			Paths: platform.Paths{CacheDir: t.TempDir()}, GateOutcome: platform.GateVerified,
		})
		if err != nil {
			t.Fatal(err)
		}
		return c
	}
	baseClient := newClient()
	base := baseClient.cacheKeyFor(http.MethodPost, "/v1/items", map[string]string{"page": "1"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"a"}`))
	cases := map[string]func(*Client) string{
		"profile": func(c *Client) string {
			c.platformSession.ProfileName = "tenant-b"
			return c.cacheKeyFor(http.MethodPost, "/v1/items", map[string]string{"page": "1"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"a"}`))
		},
		"expected identity": func(c *Client) string {
			c.platformSession.ExpectedIdentity = map[string]string{"account_id": "b"}
			return c.cacheKeyFor(http.MethodPost, "/v1/items", map[string]string{"page": "1"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"a"}`))
		},
		"observed identity": func(c *Client) string {
			c.platformSession.ObservedIdentity = map[string]string{"account_id": "b"}
			return c.cacheKeyFor(http.MethodPost, "/v1/items", map[string]string{"page": "1"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"a"}`))
		},
		"credential": func(c *Client) string {
			c.platformSession.CredentialFingerprint = "machine-keyed-fingerprint-b"
			return c.cacheKeyFor(http.MethodPost, "/v1/items", map[string]string{"page": "1"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"a"}`))
		},
		"method": func(c *Client) string {
			return c.cacheKeyFor(http.MethodGet, "/v1/items", map[string]string{"page": "1"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"a"}`))
		},
		"endpoint": func(c *Client) string {
			return c.cacheKeyFor(http.MethodPost, "/v1/orders", map[string]string{"page": "1"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"a"}`))
		},
		"query": func(c *Client) string {
			return c.cacheKeyFor(http.MethodPost, "/v1/items", map[string]string{"page": "2"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"a"}`))
		},
		"body": func(c *Client) string {
			return c.cacheKeyFor(http.MethodPost, "/v1/items", map[string]string{"page": "1"}, map[string]string{"Revision": "2026-07"}, []byte(`{"query":"b"}`))
		},
		"API version header": func(c *Client) string {
			return c.cacheKeyFor(http.MethodPost, "/v1/items", map[string]string{"page": "1"}, map[string]string{"Revision": "2027-01"}, []byte(`{"query":"a"}`))
		},
	}
	for name, change := range cases {
		if got := change(newClient()); got == base {
			t.Errorf("%s did not alter platform cache key", name)
		}
	}
}

func TestMutationInvalidatesOnlyItsResourceTag(t *testing.T) {
	c := &Client{BaseURL: "https://api.example.test", cacheDir: t.TempDir()}
	c.writeCache("/v1/orders", nil, json.RawMessage(`{"resource":"orders"}`), "application/json")
	c.writeCache("/v1/customers", nil, json.RawMessage(`{"resource":"customers"}`), "application/json")
	c.invalidateCacheResource("/v1/orders/123")
	if _, err := os.Stat(c.cacheResourceDir("/v1/orders")); !os.IsNotExist(err) {
		t.Fatalf("orders resource cache still exists after invalidation: %v", err)
	}
	if _, err := os.Stat(c.cacheResourceDir("/v1/customers")); err != nil {
		t.Fatalf("unrelated customers resource cache was removed: %v", err)
	}
	c.writeCache("/v1/orders", nil, json.RawMessage(`{"resource":"orders"}`), "application/json")
	c.invalidateCacheAfterMutation("/v1/orders/123")
	if _, err := os.Stat(c.cacheResourceDir("/v1/orders")); !os.IsNotExist(err) {
		t.Fatalf("mutation left the directly affected cache: %v", err)
	}
	if _, err := os.Stat(c.cacheResourceDir("/v1/customers")); !os.IsNotExist(err) {
		t.Fatalf("mutation left a potentially related projection cache: %v", err)
	}
}

func TestGetWithHeadersValuesPreservesRepeatedQueryParams(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got := r.URL.Query()["format"]
		if len(got) != 2 || got[0] != "blu-ray" || got[1] != "4k" {
			t.Fatalf("format query values = %#v, want [blu-ray 4k]", got)
		}
		if got := r.URL.Query().Get("country"); got != "US" {
			t.Fatalf("country = %q, want US", got)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"ok":true}`))
	}))
	t.Cleanup(server.Close)

	c := New(&config.Config{BaseURL: server.URL}, time.Second, 0)
	c.HTTPClient = server.Client()
	c.NoCache = true

	params := url.Values{
		"format":  []string{"blu-ray", "4k"},
		"country": []string{"US"},
	}
	if _, err := c.GetWithHeadersValues(context.Background(), "/titles", params, nil); err != nil {
		t.Fatalf("GetWithHeadersValues returned error: %v", err)
	}
}

// TestCrossHostRedirectStripsSensitiveHeaders is the #22 regression: Config.Headers
// (custom API keys) must not follow a cross-host 3xx. Same-host hops keep them and
// re-attach Authorization via CheckRedirect.
func TestCrossHostRedirectStripsSensitiveHeaders(t *testing.T) {
	t.Parallel()

	var targetHeaders http.Header
	target := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		targetHeaders = r.Header.Clone()
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"ok":true}`))
	}))
	t.Cleanup(target.Close)

	origin := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, target.URL+"/final", http.StatusFound)
	}))
	t.Cleanup(origin.Close)

	cfg := &config.Config{
		BaseURL:       origin.URL,
		AuthHeaderVal: "Bearer secret-token",
		Headers: map[string]string{
			"X-Api-Key":     "custom-secret",
			"X-Client-Auth": "another-secret",
		},
	}
	// Use New()'s HTTPClient so CheckRedirect runs; do not replace with origin.Client()
	// (single-host jar would not exercise cross-host hop stripping).
	c := New(cfg, time.Second, 0)
	c.NoCache = true

	if _, err := c.Get(context.Background(), "/start", nil); err != nil {
		t.Fatalf("Get after cross-host redirect: %v", err)
	}
	if targetHeaders == nil {
		t.Fatal("redirect target never received a request")
	}
	if got := targetHeaders.Get("Authorization"); got != "" {
		t.Errorf("Authorization forwarded to cross-host target: %q", got)
	}
	if got := targetHeaders.Get("X-Api-Key"); got != "" {
		t.Errorf("X-Api-Key forwarded to cross-host target: %q", got)
	}
	if got := targetHeaders.Get("X-Client-Auth"); got != "" {
		t.Errorf("X-Client-Auth forwarded to cross-host target: %q", got)
	}
}

func TestSameHostRedirectKeepsAuthAndCustomHeaders(t *testing.T) {
	t.Parallel()

	var finalHeaders http.Header
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/start" {
			http.Redirect(w, r, "/final", http.StatusFound)
			return
		}
		finalHeaders = r.Header.Clone()
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"ok":true}`))
	}))
	t.Cleanup(server.Close)

	cfg := &config.Config{
		BaseURL:       server.URL,
		AuthHeaderVal: "Bearer same-host-token",
		Headers: map[string]string{
			"X-Api-Key": "same-host-key",
		},
	}
	c := New(cfg, time.Second, 0)
	c.NoCache = true

	if _, err := c.Get(context.Background(), "/start", nil); err != nil {
		t.Fatalf("Get after same-host redirect: %v", err)
	}
	if finalHeaders == nil {
		t.Fatal("same-host final hop never received a request")
	}
	if got := finalHeaders.Get("Authorization"); got != "Bearer same-host-token" {
		t.Errorf("Authorization = %q, want Bearer same-host-token", got)
	}
	if got := finalHeaders.Get("X-Api-Key"); got != "same-host-key" {
		t.Errorf("X-Api-Key = %q, want same-host-key", got)
	}
}
